services:
  postgres:
    container_name: recycle_chain_postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: recycle_chain
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
